# Generated by Django 3.0.3 on 2020-04-03 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_book', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detail', models.TextField(null=True)),
                ('order_type', models.CharField(choices=[('order_in', 'in'), ('order_buffet', 'buffet')], max_length=255)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appModel.Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_buffet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnest', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('location', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appModel.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.IntegerField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='amount',
            field=models.IntegerField(default=20, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tax_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('net_payment', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('name', models.CharField(max_length=255)),
                ('order_buffet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appModel.Order_buffet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detail', models.TextField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='appModel.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appModel.Order')),
                ('table', models.ManyToManyField(to='appModel.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Order_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.IntegerField(max_length=10)),
                ('status', models.BooleanField(null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModel.Food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModel.Order')),
            ],
        ),
    ]
