# Generated by Django 3.0.3 on 2020-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModel', '0002_auto_20200403_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='space',
            field=models.IntegerField(),
        ),
    ]
