# Generated by Django 3.0.3 on 2020-04-17 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appModel', '0003_auto_20200403_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_buffet',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order_buffet',
            name='phone',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appModel.Order'),
        ),
        migrations.CreateModel(
            name='Customer_buffet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appModel.Customer')),
            ],
        ),
    ]
