# Generated by Django 3.0.3 on 2020-04-18 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appModel', '0004_auto_20200417_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_buffet',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_buffet',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order_buffet',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
