# Generated by Django 3.0.3 on 2020-04-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModel', '0006_auto_20200418_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_buffet',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_buffet',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
