# Generated by Django 3.0.3 on 2020-04-18 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appModel', '0009_auto_20200418_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_buffet',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 6, 55, 27, 239624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_buffet',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 18, 6, 55, 27, 239624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_buffet',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 18, 6, 55, 27, 239624, tzinfo=utc)),
        ),
    ]
