# Generated by Django 3.0.3 on 2020-04-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModel', '0012_auto_20200423_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_buffet',
            name='tax_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
